- job:
    name: group-based-policy-dsvm-aim
    parent: legacy-dsvm-base
    run: playbooks/legacy/group-based-policy-dsvm-aim/run.yaml
    post-run: playbooks/legacy/group-based-policy-dsvm-aim/post.yaml
    timeout: 7800
    required-projects:
      - x/group-based-policy
      - x/group-based-policy-automation
      - x/group-based-policy-ui
      - x/python-group-based-policy-client

- job:
    name: group-based-policy-dsvm-functional
    parent: legacy-dsvm-base
    run: playbooks/legacy/group-based-policy-dsvm-functional/run.yaml
    post-run: playbooks/legacy/group-based-policy-dsvm-functional/post.yaml
    timeout: 7800
    required-projects:
      - x/group-based-policy
      - x/group-based-policy-automation
      - x/group-based-policy-ui
      - x/python-group-based-policy-client

- job:
    name: group-based-policy-dsvm-nfp
    parent: legacy-dsvm-base
    run: playbooks/legacy/group-based-policy-dsvm-nfp/run.yaml
    post-run: playbooks/legacy/group-based-policy-dsvm-nfp/post.yaml
    timeout: 7800
    required-projects:
      - x/group-based-policy
      - x/group-based-policy-automation
      - x/group-based-policy-ui
      - x/python-group-based-policy-client

- project:
    name: x/group-based-policy
    templates:
      - openstack-python3-jobs
      - publish-to-pypi
    # REVISIT: In the jobs below, the required-projects clause is needed on
    # the master branch to select the correct version of the requirements
    # repository. Otherwise, the master version will be used. It can be
    # eliminated on the stable branches, and on the master branch once this
    # repository's master branch is based on the neutron repository's master
    # branch.
    check:
      jobs:
        - openstack-tox-pep8:
            nodeset: ubuntu-focal
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
        - openstack-tox-py38:
            nodeset: ubuntu-focal
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
        - openstack-tox-py39:
            nodeset: ubuntu-focal
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
        - openstack-tox-py310:
            nodeset: ubuntu-jammy
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
        - openstack-tox-py311:
            nodeset: ubuntu-jammy
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
        - openstack-tox-py312:
            nodeset: ubuntu-noble
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
        - group-based-policy-dsvm-functional:
            voting: false
        - group-based-policy-dsvm-aim:
            voting: false
        - group-based-policy-dsvm-nfp:
            voting: false
    gate:
      jobs:
        - openstack-tox-pep8:
            nodeset: ubuntu-focal
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
        - openstack-tox-py38:
            nodeset: ubuntu-focal
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
        - openstack-tox-py39:
            nodeset: ubuntu-focal
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
        - openstack-tox-py310:
            nodeset: ubuntu-jammy
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
        - openstack-tox-py311:
            nodeset: ubuntu-jammy
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
        - openstack-tox-py312:
            nodeset: ubuntu-noble
            required-projects:
              - name: openstack/requirements
                override-checkout: stable/2024.1
