- project:
    name: x/group-based-policy
    templates:
      - openstack-python-jobs
      - publish-to-pypi
    check:
      jobs:
        - openstack-tox-pep8:
            voting: true
        - openstack-tox-py27:
            voting: true
        - openstack-tox-py35:
            voting: true
        - legacy-group-based-policy-dsvm-functional:
            voting: false
        - legacy-group-based-policy-dsvm-aim:
            voting: false
        - legacy-group-based-policy-dsvm-nfp:
            voting: false
    gate:
      jobs:
        - openstack-tox-pep8:
            voting: true
        - openstack-tox-py27:
            voting: true
        - openstack-tox-py35:
            voting: true
